// <auto-generated />
namespace ClevelandBlogs.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class seven : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seven));
        
        string IMigrationMetadata.Id
        {
            get { return "202011240010062_seven"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
